### ISSUE TITLE
🍐 review

### ISSUE THREAD

**Issue by jonahgoldwastaken** [Vincentvanleeuwen/frontend-applications#1]
# 🍐 Repo & README
- Gitignore 👍🏻 
- Geen rotzooi in je repo, naast Vue. Svelte best, fuck de rest 👍🏻 
- Description is goed, zou eventueel iets meer over de data story kunnen gaan.
- Concept in readme 👍🏻 
- Link naar demo 👍🏻 
- [x] Features mist nog 👎🏻 
- [x] Linkjes naar packages toevoegen 👎🏻 
- [x] Acknowledgements missen nog voor dit FA, dit zijn voornamelijk acknowledgements van de vorige vakken volgens mij 👎🏻 

# 🍐 Wiki
- [x] Wiki springt van hot naar her, ik zou alle pagina's gewoon overzetten in je FA wiki 👎🏻 
- [x] Proces is te volgen, maar niet consistent bij elkaar gezet door de wisseling tussen FA en FD wiki 👎🏻 
- Proces zit in je wiki
- [x] Argumenten voor of tegen gebruik framework missen nog 👎🏻 
- Gebruik state en prop 👍🏻 
- [x] Je coolste component mist nog 👎🏻 

# 🍐 Rubric
- Nice dat je routing erin hebt zitten 👍🏻 
- Ook ziek dat je je diagram interactief hebt gekregen in Vue 👍🏻 
- Documentatie is verder heel netjes en clean geschreven 👍🏻 
- Ik heb het gevoel dat je ook wel echt snapt wat je allemaal gebruikt 👍🏻 

# 🍐 Tally
Duimpjes omhoog: 9
Duimpjes omlaag: 7
Resultaat: +2

Lekker bezig 😊

**Comment by Vincentvanleeuwen** [comment]
Thanks voor je feedback Jonah!
